"""
Fat Mex Nodes - Model Presets
Predefined configurations for each supported model family.
"""

MODEL_PRESETS = {
    "Klein 9B": {
        "unet": "flux-2-klein-9b-fp8.safetensors",
        "unet_source": "diffusion_models",
        "clip": "qwen_3_8b_fp8mixed.safetensors",
        "clip_type": "flux2",
        "vae": "flux2-vae.safetensors",
        "weight_dtype": "default",
        "sampler": "euler",
        "scheduler": "beta",
        "steps": 6,
        "cfg": 1.0,
        "sage_attention": True,
    },
    "Klein 9B True": {
        "unet": "flux2-klein-9b-true-v1-fp8.safetensors",
        "unet_source": "diffusion_models",
        "clip": "qwen_3_8b_fp8mixed.safetensors",
        "clip_type": "flux2",
        "vae": "flux2-vae.safetensors",
        "weight_dtype": "default",
        "sampler": "euler",
        "scheduler": "simple",
        "steps": 20,
        "cfg": 1.0,
        "sage_attention": False,
    },
    "Qwen Image Edit 2509": {
        "unet": "qwen_image_edit_2509_fp8_e4m3fn.safetensors",
        "unet_source": "diffusion_models",
        "clip": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
        "clip_type": "qwen_image",
        "vae": "qwen_image_vae.safetensors",
        "weight_dtype": "default",
        "sampler": "euler",
        "scheduler": "beta",
        "steps": 8,
        "cfg": 1.0,
        "sage_attention": True,
    },
    "Qwen Image Edit 2511": {
        "unet": "qwen_image_edit_2511_fp8mixed.safetensors",
        "unet_source": "diffusion_models",
        "clip": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
        "clip_type": "qwen_image",
        "vae": "qwen_image_vae.safetensors",
        "weight_dtype": "default",
        "sampler": "euler",
        "scheduler": "beta",
        "steps": 8,
        "cfg": 1.0,
        "sage_attention": True,
    },
    "Qwen Image 2512": {
        "unet": "qwen_image_2512_fp8_e4m3fn.safetensors",
        "unet_source": "diffusion_models",
        "clip": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
        "clip_type": "qwen_image",
        "vae": "qwen_image_vae.safetensors",
        "weight_dtype": "default",
        "sampler": "res_multistep",
        "scheduler": "beta",
        "steps": 8,
        "cfg": 1.0,
        "sage_attention": True,
        "model_sampling_shift": 0.6,
    },
    "Z-Image Turbo": {
        "unet": "z_image_turbo_bf16.safetensors",
        "unet_source": "diffusion_models",
        "clip": "qwen_3_4b.safetensors",
        "clip_type": "lumina2",
        "vae": "ultrafluxvae.safetensors",
        "weight_dtype": "default",
        "sampler": "euler",
        "scheduler": "ddim_uniform",
        "steps": 6,
        "cfg": 1.0,
        "sage_attention": True,
    },
    "Chroma HD": {
        "unet": "Chroma1-HD.safetensors",
        "unet_source": "unet",
        "clip": "t5/t5xxl_fp8_e4m3fn_scaled.safetensors",
        "clip_type": "chroma",
        "vae": "ultrafluxvae.safetensors",
        "weight_dtype": "default",
        "sampler": "res_multistep",
        "scheduler": "simple",
        "steps": 3,
        "cfg": 0.15,
        "sage_attention": True,
    },
    "Qwen Rapid AIO": {
        "unet": None,
        "unet_source": "checkpoints",
        "checkpoint": "Qwen-Rapid-AIO-NSFW-v18.safetensors",
        "clip": None,
        "clip_type": None,
        "vae": None,
        "weight_dtype": "default",
        "sampler": "euler",
        "scheduler": "simple",
        "steps": 6,
        "cfg": 1.0,
        "sage_attention": True,
    },
    "Qwen Image 2.0 (Placeholder)": {
        "unet": "qwen_image_2.0_fp8.safetensors",
        "unet_source": "diffusion_models",
        "clip": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
        "clip_type": "qwen_image",
        "vae": "qwen_image_vae.safetensors",
        "weight_dtype": "default",
        "sampler": "euler",
        "scheduler": "beta",
        "steps": 8,
        "cfg": 1.0,
        "sage_attention": False,
    },
}

PRESET_NAMES = list(MODEL_PRESETS.keys())

RESOLUTION_PRESETS = {
    "1024x1024 (Square)": (1024, 1024),
    "768x1344 (Portrait 9:16)": (768, 1344),
    "1344x768 (Landscape 16:9)": (1344, 768),
    "832x1216 (Portrait 2:3)": (832, 1216),
    "1216x832 (Landscape 3:2)": (1216, 832),
    "896x1152 (Portrait 7:9)": (896, 1152),
    "1152x896 (Landscape 9:7)": (1152, 896),
    "Custom": (0, 0),
}

RESOLUTION_NAMES = list(RESOLUTION_PRESETS.keys())
